// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZVKJfshaC-HGrp-6WbSHFCF9NgODPED8',
    appId: '1:655374477514:web:146c8c7f05838b3ce3ac33',
    messagingSenderId: '655374477514',
    projectId: 'to-do-application-6f9b3',
    authDomain: 'to-do-application-6f9b3.firebaseapp.com',
    storageBucket: 'to-do-application-6f9b3.appspot.com',
    measurementId: 'G-TX3Z79HX1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRKz7usV8xWc5b2MZINEWzIIpQJFrYz5g',
    appId: '1:655374477514:android:ae8c7663426fe96ee3ac33',
    messagingSenderId: '655374477514',
    projectId: 'to-do-application-6f9b3',
    storageBucket: 'to-do-application-6f9b3.appspot.com',
  );
}
